FROM ubuntu:24.04

RUN apt-get update &&\
    apt-get install -y\
    build-essential \
    tar \
    libtool \
    net-tools \
    curl \
    vim \
    make \
    libc-dev \
    iputils-ping \
    tcpdump \
    libpcap-dev \
    iproute2 \
    gdb \
    cmake \
    gcc \
    g++ \
    clang \
    libcurl4-openssl-dev
 
WORKDIR /tmp

    

